### ISSUE TITLE
Tests are broken

### ISSUE THREAD

**Issue by jugmac00** [zopefoundation/z3c.coverage#14]
I do not use this package - I just ran `tox` on all Zope projects:
https://jugmac00.github.io/blog/testing-the-tox-4-pre-release-at-scale/

Is this package still needed or maybe can we archive it?

There is the excellent `coverage.py` by Ned - or maybe I miss something what this package does what `coverage.py` cannot do.

Anybody still uses this package?

oh holy...

```
❯ all-repos-grep -C all-repos-zope.json z3c.coverage --repos-with-matches
output_zope/zopefoundation/ZODB
output_zope/zopefoundation/cipher.encryptingstorage
output_zope/zopefoundation/cipher.lazydate
output_zope/zopefoundation/cipher.longrequest
output_zope/zopefoundation/five.taskqueue
output_zope/zopefoundation/keas.profile
output_zope/zopefoundation/z3c.authenticator
output_zope/zopefoundation/z3c.coverage
output_zope/zopefoundation/z3c.form
output_zope/zopefoundation/z3c.formwidget.ckeditor
output_zope/zopefoundation/z3c.layer.pagelet
output_zope/zopefoundation/z3c.layer.ready2go
output_zope/zopefoundation/z3c.macro
output_zope/zopefoundation/z3c.menu.ready2go
output_zope/zopefoundation/z3c.pagelet
output_zope/zopefoundation/z3c.password
output_zope/zopefoundation/z3c.schema
output_zope/zopefoundation/z3c.table
output_zope/zopefoundation/z3c.template
output_zope/zopefoundation/z3c.traverser
output_zope/zopefoundation/z3c.wizard
output_zope/zopefoundation/zope.app.exception
output_zope/zopefoundation/zope.app.generations
output_zope/zopefoundation/zope.app.http
output_zope/zopefoundation/zope.app.publisher
output_zope/zopefoundation/zope.app.security
output_zope/zopefoundation/zope.authentication
output_zope/zopefoundation/zope.browsermenu
output_zope/zopefoundation/zope.browserpage
output_zope/zopefoundation/zope.browserresource
output_zope/zopefoundation/zope.component
output_zope/zopefoundation/zope.componentvocabulary
output_zope/zopefoundation/zope.container
output_zope/zopefoundation/zope.errorview
output_zope/zopefoundation/zope.file
output_zope/zopefoundation/zope.formlib
output_zope/zopefoundation/zope.index
output_zope/zopefoundation/zope.location
output_zope/zopefoundation/zope.pagetemplate
output_zope/zopefoundation/zope.password
output_zope/zopefoundation/zope.principalannotation
output_zope/zopefoundation/zope.principalregistry
output_zope/zopefoundation/zope.ptresource
output_zope/zopefoundation/zope.security
output_zope/zopefoundation/zope.site
output_zope/zopefoundation/zope.testbrowser
output_zope/zopefoundation/zope.traversing
output_zope/zopefoundation/zope.untrustedpython
```

```
❯ tox -e py36 -rvv
using tox.ini: /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/tox.ini (pid 345)
using tox-3.23.0 from /home/jugmac00/opt/tox/lib/python3.8/site-packages/tox/__init__.py (pid 345)
GLOB start: packaging 
GLOB sdist-make: /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/setup.py
[355] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage$ /home/jugmac00/opt/tox/bin/python setup.py sdist --formats=zip --dist-dir /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/dist >.tox/log/GLOB-0.log
running sdist
running egg_info
writing src/z3c.coverage.egg-info/PKG-INFO
writing dependency_links to src/z3c.coverage.egg-info/dependency_links.txt
writing entry points to src/z3c.coverage.egg-info/entry_points.txt
writing namespace_packages to src/z3c.coverage.egg-info/namespace_packages.txt
writing requirements to src/z3c.coverage.egg-info/requires.txt
writing top-level names to src/z3c.coverage.egg-info/top_level.txt
reading manifest file 'src/z3c.coverage.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
warning: no files found matching '*.txt'
warning: no previously-included files matching '*.pyc' found anywhere in distribution
writing manifest file 'src/z3c.coverage.egg-info/SOURCES.txt'
running check
creating z3c.coverage-3.0.dev0
creating z3c.coverage-3.0.dev0/src
creating z3c.coverage-3.0.dev0/src/z3c
creating z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
creating z3c.coverage-3.0.dev0/src/z3c/coverage
creating z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
creating z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
copying files to z3c.coverage-3.0.dev0...
copying .coveragerc -> z3c.coverage-3.0.dev0
copying .travis.yml -> z3c.coverage-3.0.dev0
copying AUTHORS.rst -> z3c.coverage-3.0.dev0
copying CHANGES.rst -> z3c.coverage-3.0.dev0
copying COPYRIGHT.rst -> z3c.coverage-3.0.dev0
copying LICENSE.rst -> z3c.coverage-3.0.dev0
copying MANIFEST.in -> z3c.coverage-3.0.dev0
copying README.rst -> z3c.coverage-3.0.dev0
copying bootstrap.py -> z3c.coverage-3.0.dev0
copying buildout.cfg -> z3c.coverage-3.0.dev0
copying setup.cfg -> z3c.coverage-3.0.dev0
copying setup.py -> z3c.coverage-3.0.dev0
copying tox.ini -> z3c.coverage-3.0.dev0
copying src/z3c/__init__.py -> z3c.coverage-3.0.dev0/src/z3c
copying src/z3c.coverage.egg-info/PKG-INFO -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/SOURCES.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/dependency_links.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/entry_points.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/namespace_packages.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/not-zip-safe -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/requires.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c.coverage.egg-info/top_level.txt -> z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info
copying src/z3c/coverage/README.txt -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/__init__.py -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/coveragediff.py -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/coveragediff.txt -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/coveragereport.py -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/sample.py -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/sampleinput.coverage -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/tests.py -> z3c.coverage-3.0.dev0/src/z3c/coverage
copying src/z3c/coverage/moresampleinput/z3c.coverage.__init__.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/moresampleinput/z3c.coverage.coveragediff.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/moresampleinput/z3c.coverage.coveragereport.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/moresampleinput/z3c.coverage.fakenewmodule.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/moresampleinput/z3c.coverage.faketestedmodule.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/moresampleinput/z3c.coverage.tests.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput
copying src/z3c/coverage/sampleinput/decoy.txt -> z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
copying src/z3c/coverage/sampleinput/z3c.coverage.__init__.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
copying src/z3c/coverage/sampleinput/z3c.coverage.coveragediff.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
copying src/z3c/coverage/sampleinput/z3c.coverage.coveragereport.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
copying src/z3c/coverage/sampleinput/z3c.coverage.tests.cover -> z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput
Writing z3c.coverage-3.0.dev0/setup.cfg
creating /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/dist
creating '/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/dist/z3c.coverage-3.0.dev0.zip' and adding 'z3c.coverage-3.0.dev0' to it
adding 'z3c.coverage-3.0.dev0'
adding 'z3c.coverage-3.0.dev0/src'
adding 'z3c.coverage-3.0.dev0/CHANGES.rst'
adding 'z3c.coverage-3.0.dev0/bootstrap.py'
adding 'z3c.coverage-3.0.dev0/PKG-INFO'
adding 'z3c.coverage-3.0.dev0/COPYRIGHT.rst'
adding 'z3c.coverage-3.0.dev0/.coveragerc'
adding 'z3c.coverage-3.0.dev0/tox.ini'
adding 'z3c.coverage-3.0.dev0/AUTHORS.rst'
adding 'z3c.coverage-3.0.dev0/.travis.yml'
adding 'z3c.coverage-3.0.dev0/LICENSE.rst'
adding 'z3c.coverage-3.0.dev0/MANIFEST.in'
adding 'z3c.coverage-3.0.dev0/setup.py'
adding 'z3c.coverage-3.0.dev0/setup.cfg'
adding 'z3c.coverage-3.0.dev0/README.rst'
adding 'z3c.coverage-3.0.dev0/buildout.cfg'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info'
adding 'z3c.coverage-3.0.dev0/src/z3c'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/namespace_packages.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/SOURCES.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/PKG-INFO'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/dependency_links.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/entry_points.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/requires.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/not-zip-safe'
adding 'z3c.coverage-3.0.dev0/src/z3c.coverage.egg-info/top_level.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage'
adding 'z3c.coverage-3.0.dev0/src/z3c/__init__.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/tests.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sample.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/coveragediff.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/coveragediff.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/coveragereport.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput.coverage'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/__init__.py'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/README.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput/z3c.coverage.tests.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput/decoy.txt'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput/z3c.coverage.coveragediff.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput/z3c.coverage.coveragereport.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/sampleinput/z3c.coverage.__init__.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.tests.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.coveragediff.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.faketestedmodule.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.coveragereport.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.fakenewmodule.cover'
adding 'z3c.coverage-3.0.dev0/src/z3c/coverage/moresampleinput/z3c.coverage.__init__.cover'
removing 'z3c.coverage-3.0.dev0' (and everything under it)

GLOB finish: packaging  after 0.17 seconds
copying new sdistfile to '/home/jugmac00/.tox/distshare/z3c.coverage-3.0.dev0.zip'
package .tmp/package/1/z3c.coverage-3.0.dev0.zip links to dist/z3c.coverage-3.0.dev0.zip (/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox)
python3.6 (/usr/bin/python3.6) is {'executable': '/usr/bin/python3.6', 'implementation': 'CPython', 'version_info': [3, 6, 9, 'final', 0], 'version': '3.6.9 (default, Jan 26 2021, 15:33:00) \n[GCC 8.4.0]', 'is_64': True, 'sysplatform': 'linux', 'extra_version_info': None}
py36 uses /usr/bin/python3.6
py36 start: getenv /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36
py36 cannot reuse: -r flag
py36 create: /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36
setting PATH=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[359] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox$ /home/jugmac00/opt/tox/bin/python -m virtualenv --no-download --python /usr/bin/python3.6 py36
created virtual environment CPython3.6.9.final.0-64 in 100ms
  creator CPython3Posix(dest=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36, clear=False, no_vcs_ignore=False, global=False)
  seeder FromAppData(download=False, pip=bundle, setuptools=bundle, wheel=bundle, via=copy, app_data_dir=/home/jugmac00/.local/share/virtualenv)
    added seed packages: pip==21.0.1, setuptools==54.2.0, wheel==0.36.2
  activators BashActivator,CShellActivator,FishActivator,PowerShellActivator,PythonActivator,XonshActivator
py36 installdeps: zope.testrunner, zope.testing
setting PATH=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[366] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage$ /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin/python -m pip install zope.testrunner zope.testing
Collecting zope.testrunner
  Using cached zope.testrunner-5.3.0-py2.py3-none-any.whl (215 kB)
Collecting zope.testing
  Using cached zope.testing-4.9-py2.py3-none-any.whl (50 kB)
Requirement already satisfied: setuptools in ./.tox/py36/lib/python3.6/site-packages (from zope.testing) (54.2.0)
Collecting six
  Using cached six-1.15.0-py2.py3-none-any.whl (10 kB)
Collecting zope.interface
  Using cached zope.interface-5.4.0-cp36-cp36m-manylinux2010_x86_64.whl (251 kB)
Collecting zope.exceptions
  Using cached zope.exceptions-4.4-py2.py3-none-any.whl (18 kB)
Installing collected packages: zope.interface, zope.exceptions, six, zope.testrunner, zope.testing
Successfully installed six-1.15.0 zope.exceptions-4.4 zope.interface-5.4.0 zope.testing-4.9 zope.testrunner-5.3.0
py36 finish: getenv /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36 after 2.09 seconds
py36 start: installpkg /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip
py36 inst: /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip
write config to /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/.tox-config1 as '9b56b084b98cbe6dc10d740ad48815b9146a252cbfc3d78e9ffd42a36d965d1f /usr/bin/python3.6\n3.23.0 0 0 0\n00000000000000000000000000000000 zope.testrunner\n00000000000000000000000000000000 zope.testing'
setting PATH=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[375] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage$ /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin/python -m pip install --exists-action w .tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip
Processing ./.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip
Requirement already satisfied: setuptools in ./.tox/py36/lib/python3.6/site-packages (from z3c.coverage==3.0.dev0) (54.2.0)
Collecting coverage>=4.0
  Using cached coverage-5.5-cp36-cp36m-manylinux2010_x86_64.whl (240 kB)
Building wheels for collected packages: z3c.coverage
  Building wheel for z3c.coverage (setup.py) ... done
  Created wheel for z3c.coverage: filename=z3c.coverage-3.0.dev0-py3-none-any.whl size=46990 sha256=e0b413c027c9a6df56ef6e4d1891d95a5ef8eb54c76bc856aa894f9ec5bc1587
  Stored in directory: /home/jugmac00/.cache/pip/wheels/dd/6a/5c/8413748d09163210216914b3be2163e738e6d01a06c3f8a192
Successfully built z3c.coverage
Installing collected packages: coverage, z3c.coverage
Successfully installed coverage-5.5 z3c.coverage-3.0.dev0
py36 finish: installpkg /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip after 1.61 seconds
py36 start: envreport 
setting PATH=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[393] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage$ /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin/python -m pip freeze >.tox/py36/log/py36-0.log
py36 finish: envreport  after 0.22 seconds
py36 installed: coverage==5.5,six==1.15.0,z3c.coverage @ file:///home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip,zope.exceptions==4.4,zope.interface==5.4.0,zope.testing==4.9,zope.testrunner==5.3.0
py36 start: run-test-pre 
py36 run-test-pre: PYTHONHASHSEED='2764790421'
py36 finish: run-test-pre  after 0.00 seconds
py36 start: run-test 
py36 run-test: commands[0] | zope-testrunner --test-path=src
setting PATH=/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin:/home/jugmac00/.cargo/bin:/home/jugmac00/.local/bin:/home/jugmac00/bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
[395] /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage$ /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin/zope-testrunner --test-path=src
Running zope.testrunner.layer.UnitTests tests:
  Set up zope.testrunner.layer.UnitTests in 0.000 seconds.
/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  text = cgi.escape(file.read())
/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  text = cgi.escape(file.read())
/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  text = cgi.escape(file.read())
coveragereport:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
coveragereport:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
coveragereport:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead


Failure in test /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/README.txt
Failed doctest test for README.txt
  File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/README.txt", line 0

----------------------------------------------------------------------
File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/README.txt", line 54, in README.txt
Failed example:
    coveragereport.main([
        inputFile, outputDir, '-q',
        '--path-alias=/home/mg/src/zopefoundation/z3c.coverage/src/z3c/coverage=%s'
            % os.path.dirname(z3c.coverage.__file__),
        '--strip-prefix=%s'
            % os.path.realpath(os.path.dirname(os.path.dirname(
                os.path.dirname(z3c.coverage.__file__)))),
    ])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest README.txt[12]>", line 7, in <module>
        os.path.dirname(z3c.coverage.__file__)))),
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 634, in main
        make_coverage_reports(path, report_path, opts=opts)
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 555, in make_coverage_reports
        tree = load_coverage(path, opts=opts)
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 545, in load_coverage
        cov.load()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/control.py", line 426, in load
        self._data.read()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 753, in read
        with self._connect():       # TODO: doesn't look right
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 298, in _connect
        self._open_db()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 266, in _open_db
        self._read_db()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 270, in _read_db
        with self._dbs[get_thread_id()] as db:
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1037, in __enter__
        self._connect()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1025, in _connect
        self.execute("pragma journal_mode=off").close()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1082, in execute
        raise CoverageException("Couldn't use data file {!r}: {}".format(self.filename, msg))
    coverage.misc.CoverageException: Couldn't use data file '/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/sampleinput.coverage': Looks like a coverage 4.x data file. Are you mixing versions of coverage?
----------------------------------------------------------------------
File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/README.txt", line 62, in README.txt
Failed example:
    print('\n'.join(sorted(os.listdir(outputDir))))
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest README.txt[13]>", line 1, in <module>
        print('\n'.join(sorted(os.listdir(outputDir))))
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/tmp-z3c.coverage-report-0lmlrcbx/report'
----------------------------------------------------------------------
File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/README.txt", line 75, in README.txt
Failed example:
    coveragereport.main([
        inputFile, outputDir, '-q',
        '--path-alias=/home/mg/src/zopefoundation/z3c.coverage/src/z3c/coverage=%s'
            % os.path.dirname(z3c.coverage.__file__),
    ])
Exception raised:
    Traceback (most recent call last):
      File "/usr/lib/python3.6/doctest.py", line 1330, in __run
        compileflags, 1), test.globs)
      File "<doctest README.txt[14]>", line 4, in <module>
        % os.path.dirname(z3c.coverage.__file__),
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 634, in main
        make_coverage_reports(path, report_path, opts=opts)
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 555, in make_coverage_reports
        tree = load_coverage(path, opts=opts)
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py", line 545, in load_coverage
        cov.load()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/control.py", line 426, in load
        self._data.read()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 753, in read
        with self._connect():       # TODO: doesn't look right
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 298, in _connect
        self._open_db()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 266, in _open_db
        self._read_db()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 270, in _read_db
        with self._dbs[get_thread_id()] as db:
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1037, in __enter__
        self._connect()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1025, in _connect
        self.execute("pragma journal_mode=off").close()
      File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/coverage/sqldata.py", line 1082, in execute
        raise CoverageException("Couldn't use data file {!r}: {}".format(self.filename, msg))
    coverage.misc.CoverageException: Couldn't use data file '/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/sampleinput.coverage': Looks like a coverage 4.x data file. Are you mixing versions of coverage?

/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  text = cgi.escape(file.read())


Failure in test doctest_syntax_highlight_with_enscript (z3c.coverage.tests)
Failed doctest test for z3c.coverage.tests.doctest_syntax_highlight_with_enscript
  File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/tests.py", line 250, in doctest_syntax_highlight_with_enscript

----------------------------------------------------------------------
File "/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/tests.py", line 269, in z3c.coverage.tests.doctest_syntax_highlight_with_enscript
Failed example:
    print(output)  # doctest:+ELLIPSIS +NORMALIZE_WHITESPACE
    # this will fail if you don't have enscript in your $PATH
Expected:
    <BLANKLINE>
    <I><FONT COLOR="#B22222"># Make a package.
    </FONT></I><I><FONT COLOR="#B22222"># -*- coding: utf-8 -*-
    </FONT></I><I><FONT COLOR="#B22222"># Some umlauts for testing: ...
    </FONT></I>
Got:
    # Make a package.
    # -*- coding: utf-8 -*-
    # Some umlauts for testing: ä ö ü € ௲
    <BLANKLINE>

/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:431: DeprecationWarning: cgi.escape is deprecated, use html.escape instead
  text = cgi.escape(file.read())
/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/coveragereport.py:74: ResourceWarning: unclosed file <_io.TextIOWrapper name='/home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/lib/python3.6/site-packages/z3c/coverage/sample.py' mode='r' encoding='UTF-8'>
  value = self.func(obj)
  Ran 20 tests with 2 failures, 0 errors and 0 skipped in 0.080 seconds.
Tearing down left over layers:
  Tear down zope.testrunner.layer.UnitTests in 0.000 seconds.
ERROR: InvocationError for command /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/py36/bin/zope-testrunner --test-path=src (exited with code 1)
py36 finish: run-test  after 0.28 seconds
py36 start: run-test-post 
py36 finish: run-test-post  after 0.00 seconds
__________________________________________ summary ___________________________________________
ERROR:   py36: commands failed
cleanup /home/jugmac00/All/output_zope/zopefoundation/z3c.coverage/.tox/.tmp/package/1/z3c.coverage-3.0.dev0.zip
```

**Comment by mgedmin** [comment]
IIRC the test suite relies on `enscript` being installed on your system.  The other errors look like some kind of coverage version mismatch -- oh dear, did we really commit a binary coverage file into our git?  yes we did!  wonderful foresight, reminds me of the test suite that started failing when the git-committed self-signed SSL certificate expired.  anyway.

**Comment by mgedmin** [comment]
We have compatibility issues with coverage >= 5.0: https://github.com/zopefoundation/z3c.coverage/issues/15
